### ISSUE TITLE
The format of the input file

### ISSUE THREAD

**Issue by Mia-yao** [Lee-CBG/catELMo#1]
Hi Pengfei,

I think your work is very impressive and I am eager to use your model in my research! Could you please provide more details regarding the format of the input file while using catELMo to calculate the embedding of TCR sequences?

To be more specific, in the instruction, you mentioned the input file 'dat = pd.read_csv('./path/of/binding/affinity/prediction/data.csv')', it would be very nice if you could provide an example of this 'data.csv' file. Besides, is it necessary to include peptide info in the input file? Can I only input TCR sequences and get their embedding, since that's what I am most interested in?

Thank you so much in advance! Looking forward to hearing from you soon.
Mingyao

**Comment by pzhang84** [comment]
Hi Mingyao,

Thank you for your interest in our work! Regarding the input file format for using catELMo to calculate the embedding of TCR sequences, here are some details:

The 'data.csv' file should be a CSV file containing a column with TCR sequences. For example, it might look like this:

```
tcr
CASSLGNEQF
CASSLGVATGELF
CASSQEEGGGSWGNTIYF
CASSQEGLAGASQYF
```

To compute the embedding and store it as one column of your data:
`dat['tcr_embeds'] = dat[['tcr']].applymap(lambda x: catELMo_embedding(x))['tcr']`

Yes, you can just provide the TCR sequences to the model and get embeddings for your tasks. 

Hope this helps,

Pengfei

**Comment by Mia-yao** [comment]
Hi Pengfei,

Thank you so much for your prompt response! Your explanation is very clear and I believe your work would be of great use to my research!

Hope you all the best!
Mingyao
